### ISSUE TITLE
Команда проєкта

### ISSUE THREAD

**Issue by denniksam** [denniksam/WPF-121#1]
Учасники проєкта мають:
- [x] домовитись про співпрацю
- [ ] створити репозиторії
- [x] обмінятись посиланнями

**Comment by gorin197** [comment]
Принято к исполнению

**Comment by YuriySolomon** [comment]
Вітаю. Дякую за довіру)

**Comment by denniksam** [comment]
Виконано

**Comment by Sveta1717** [comment]
Зроблено!
